### ISSUE TITLE
메인 페이지

### ISSUE THREAD

**Issue by haemalgeumi** [ChatCode9/ChatCode-frontend#15]
### 📄 Describe

메인 페이지 퍼블리싱 작업과 api 작업

### ✅ Tasks

- [x] 슬라이더 기능
- [x] 게시글 리스트 및 유튜브 연결
- [x] #37

**Comment by gusrl6394** [comment]
로고 크기가 알맞은것으로 하는게 가장 최선의 방법이겠지만
원본 위아래 짤리겠지만 아래와 같이 하면 사진처럼 그나마 좌우 여백이 없는 사진이 나옵니다

```diff
export default function Slider() {
  ....
 const StyledSwiperSlide = styled(SwiperSlide)`
  ....
  img {
    display: block;
-   width: 100%;
-   height: 100%;
+   width: 1000px;
+   height: 1000%;
    object-fit: contain;
  }
```

![slider_1](https://github.com/ChatCode9/ChatCode-frontend/assets/20663508/99f7be6e-7d7b-4369-9a78-b4b1dda196af)
![slider_2](https://github.com/ChatCode9/ChatCode-frontend/assets/20663508/5405ed2e-af99-4534-8e59-363526063eec)
